### ISSUE TITLE
Allow use of rust keywords (like type) in records/variants

### ISSUE THREAD

**Issue by lastmjs** [demergent-labs/cdk_framework#13]

**Comment by bdemann** [comment]
Thoughts from my notes, I'll copy them over here for posterity

In the generated rust file we need to change:
`let abstract_ = _kybra_unwrap_rust_python_result(self.get_item("abstract_", vm), vm);`
to say
`let abstract_ = _kybra_unwrap_rust_python_result(self.get_item("abstract", vm), vm);`

because the result from the vm will not have the underscore and we need to assign that value to a rust variable that does have the underscore. Both try_from and try_into have similar things and both need to updated.

The other file has
`py_data_structure.set_item("abstract_", abstract_, vm);`
which needs to become
`py_data_structure.set_item("abstract", abstract_, vm);`

And it looks like we will also have to handle the case where the keywords are both in rust and in the original language.
